name: C++ CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install compiler
        run: |
          sudo apt update
          sudo apt install -y g++

      - name: Compile program
        run: g++ "class Barang.cpp" -o program

      - name: Run program (Testing)
        run: ./program
